### ISSUE TITLE
Some fixes about GoldServer

### ISSUE THREAD

**Issue by joelwurtz** [koraktor/steam-condenser#12]
Hey,

I have been trying to use this api (java) but i got some few problem. So after i  have downloaded the source code, i have made some modifications in respond to the lastest updated of hlds :

Here they are :

 SERVERQUERY_GETCHALLENGE doesn't long work on GoldSourceServer, a way to get the challenge is to send a A2S_PLAYER request with à challenge of -1

Now A2S_INFO need a trailing null/zero byte , so when you get the databytes if the kind of request is A2S_INFO you have to add 0x00 at the end

And finally in the java source code when you send A2S_INFO you expect to have a S2A_INFO_BasePacket class but you return a S2A_INFO2_Packet so i have change the expected class, but maybe it's the wrong way.

Source : http://developer.valvesoftware.com/wiki/Half-life_1_Engine_Bug_Reports#A2S_INFO_issues

PS : If you see huge mistake in vocabular or gramar, it's normal i'm french ...

**Comment by koraktor** [comment]
I fixed the second and third problem mentioned by you in 91f70752fa0d6b502ce77e99ee74b101b3838e46.
The first problem is a bug in HLDS and I most probably won't fix this in the library until Valve announces that this is an intentional change in the protocol. Until that the `GameServer.handleResponse()` method should work around this issue.
