### ISSUE TITLE
Too many open files on exceptions

### ISSUE THREAD

**Issue by maxencehenneron** [koraktor/steam-condenser#205]
Hi everyone, I currently have a problem with steam condenser. After 1024 exceptions (like portUnreachable, timeout...) I get a too many open files exception that freeze my program (as it is a server).. how can I fix this ? :)

**Comment by gallomimia** [comment]
A simple, easy way is to change the limit on open files with: ulimit -f 2048 (or some other number) You generally need root permission to do this. It sounds to me that steam condenser is failing to close some log files when exceptions are thrown. What language implementation are you working with?

**Comment by maxencehenneron** [comment]
I'm using Java. I did that, well, it works, but there's like 14000 exceptions / month on my program (It's a server program) so, isn't that dangerous ?

**Comment by koraktor** [comment]
Setting `ulimit` shouldn't be necessary. What exactly are you doing? Querying servers? RCON?

**Comment by gallomimia** [comment]
Yes. There must be a resource leak somewhere. That seems odd for Java. Does
the process stay running for months on end??

Sent from my iPhone

On 2013-03-17, at 13:33, Maxence Henneron notifications@github.com wrote:

I'm using Java. I did that, well, it works, but there's like 14000
exceptions / month on my server (It's a server status) so, isn't that
dangerous ?

—
Reply to this email directly or view it on
GitHubhttps://github.com/koraktor/steam-condenser/issues/205#issuecomment-15029065
.

**Comment by maxencehenneron** [comment]
Well here is my code : http://pastebin.com/z25Q2Pxw

So yes, I'm just Querying servers, and my process stay running everytime (a 4 month uptime).. Thanks for helping me ! :)
(I call this class with online = new SteamInfos(port).getOnline();)

**Comment by gallomimia** [comment]
1. Java has garbage collection, so objects should be released automatically when your program gets done with them. The file handler resource leak should not be happening. Having a thousand files open at once is just plain not okay. So, when I suggested raising the limit, this was just as a temporary measure. You can raise it as high as you want, but yes, this is dangerous. I only meant for you to do this as a way to keep things running while you troubleshoot the cause of this problem.
2. Your code provided has no file handlers, so where is the open file limit getting hit? A stack trace might be useful.
3. What is edenslave? It has been 15 years since I did anything with java so I'm way out of date with any current tools and libraries. Is this your code or a 3rd party?

I have also not looked at the java version of this code. Something, somewhere, is opening files at an alarming rate. Trace it down, and get those files closed when they're finished. Where are these files ending up? Is it not filling your disk with files containing who-knows-what all over the place? What reason does the program have for dealing with files at all?

**Comment by Yeggstry** [comment]
Well I'm not sure how your code is compiling, since server isn't initialized for the server.disconnect() calls in the catch statements.

Aside from that, server.disconnect doesn't actually do anything; the abstract superclass (Server) contains no code for that method, and none of the subclasses (GameServer or GoldSrcServer) implement it.

The comment for this method states: "In the base implementation this does nothing, only connection-based communication channels have to be disconnected.", not sure if this relevant for this scenario, I don't know much about the source servers.

It would be useful to know how you are calling this class as well. If you are looping through a collection of servers to query its possible that this is the cause. If you're calling it on an ad-hoc basis Java should handle the garbage collection without any problems.

**Comment by danielsawan** [comment]
sorry gallomimia  but i don't agree with you on 2 things :
Java GC don't release socket connection. You have to close connection in a finally block. 
And the ulimit tricks will only push the problem to later and will not fix the real issue of the Too many open files exception.
You really have to find those connexion you don't close and close them.

By memory i think you can use lsof | wc -l to see how many open file you have.

**Comment by koraktor** [comment]
I found the problem, `GameServer` is leaking UDP sockets.

@danielsawan @gallomimia The GC should be able to handle disconnects, because `Server#finalize()` calls `Server#disconnect()`. The GC itself isn't able to detect resource leaks. The main problem here is, that the GC isn't called when a resource leaks (or ulimit is reached), it's job is to clean up memory.
