### ISSUE TITLE
Ruby 2.0 compatibility

### ISSUE THREAD

**Issue by nTraum** [koraktor/steam-condenser#213]
Correct me if I'm wrong, but `steam-condenser` currently does not work with Ruby 2.0 simply because of the fact that `bzip2-ruby` is not being updated, right?

I see you commited a fix to this, but the maintainer seems to be inactive for a while now.
With Ruby 2.0 being stable now, have you ever thought of forking the repository and releasing a updated version of this gem? Maybe there are other gems available to that are 2.0 compatible?

Would really like to see `steam-condenser` working on 2.0. :)

Thanks for your time.

**Comment by koraktor** [comment]
:+1:

@brianmario Any chance to get a new version of bzip2-ruby soon?

**Comment by brianmario** [comment]
Hey sorry... bzip2-ruby's master branch is in some totally jacked up state which segfaults due to some corruption or double-free somewhere. I'm not even sure when it started happening. The original code was so atrocious I made as little change as possible to get it running on 1.9 then a couple of others have come in and done some small refactoring. Also, the original code was never designed to run on 1.9 (or any other Ruby VM than Ruby 1.8 MRI for that matter) so tracking down this issue has proven difficult... There's lots of poking around Ruby's internal data structures.

As far as I can tell, steam-condenser uses bzip2-ruby to just decompress data wholesale (not streaming). I'm unfortunately unaware of any other bzip2 libraries for Ruby that do this - and if that's the case I think it'll be pretty easy to whip up a simple wrapper around libbz2's `BZ2_bzBuffToBuffCompress` and `BZ2_bzBuffToBuffDecompress` functions using FFI. I started one [here](https://gist.github.com/brianmario/5833373) which works fine except for decompression - there's no good way to know how large to make the output buffer ahead of time using these utility functions from libbz2 so I just ended up using `input.bytesize*10` (see [here](https://gist.github.com/brianmario/5833373#file-bzip2-rb-L155)) which is terrible :P In any case, this could be a good starting point.

**Comment by koraktor** [comment]
@brianmario Would you mind if I ported the code from your Gist into my [rbzip2 gem](https://github.com/koraktor/rbzip2)? I started it as a fun project to provide a pure Ruby implementation of BZip2, but it seems like it could be of more value by now.

**Comment by brianmario** [comment]
Not at all, please do! :)
Maybe someday when I have some more time I'll refactor the crap out of bzip2-ruby and make it useable again, heh. Sorry for the trouble!

**Comment by koraktor** [comment]
Turning rbzip2 into some sort of "multi-bzip2" seems to be a good short term solution. I'll try to release version 0.3.0 soon with support for @brianmario's FFI solution, a fallback to the old bzip2-ruby gem and a last resort with the original pure Ruby implementation which is pretty slow.

**Comment by koraktor** [comment]
After doing some tests with dozens of servers picked randomly from the master servers it seems that BZip2 is no longer used by Source game servers. Thus I'm tending to make bzip2-ruby optional in the next patch version of the gem. After that, I'll probably remove BZip2 support entirely or replace it with rbzip2 for version 2.

**Comment by koraktor** [comment]
For now, bzip2-ruby [has been removed](https://github.com/koraktor/steam-condenser-ruby/commit/41593e71bf72bb75f35b671e2a87e026468c74e6) from the dependencies of the Ruby gem. This might change again if there's any indication that compressed packets are still used. Until that happens, I guess it's safe to say that Steam Condenser is working on Ruby 2.0.0 (and JRuby).

**Comment by nTraum** [comment]
You're the man! Appreciate it, thanks.
