### ISSUE TITLE
[Ruby] Rcon authenticated in GoldSrc

### ISSUE THREAD

**Issue by jpalumickas** [koraktor/steam-condenser#223]
Hello,

In `steam-condenser/servers/goldsrc_server.rb` on method `rcon_auth` never set `@rcon_authenticated` to true, so we cannot get extended players list.

I have an idea how to check if authenticated or not. Maybe we can instantly make `rcon_exec('status')` on `rcon_auth` and if it's not rescued to `RCONNoAuthException`, then we can set `@rcon_authenticated = true`

**Comment by koraktor** [comment]
There's no way to check if a RCON "connection" to a GoldSrc server is authenticated, that's why [`GameServer#update_players`](https://github.com/koraktor/steam-condenser-ruby/blob/1.3.7/lib/steam/servers/game_server.rb#L265) accepts a parameter for the RCON password. That way you can authenticate if you need the additional player information.

**Comment by jpalumickas** [comment]
I tried and there was no extended information, so this is a bug. I gave to you an idea, how to check :)

**Comment by koraktor** [comment]
Are you sure this is caused by not sending the RCON request at all? Please enable logging / `$DEBUG` and check the output.
