### ISSUE TITLE
SteamID init should match for ids in a regex?

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#31]
Hey,
at the moment SteamID is init with:
      if id.is_a? Numeric
        @steam_id64 = id
      else
        @custom_url = id.downcase
      end

The Problem is that ids in a String are set as custom_url, perhaps there should be some regex?
id.match(/\d{17}/) (if steam_ids are every time 17 digits long?)

Or did i miss something? Thanks for your help!

**Comment by idev** [comment]
Hm, i generelly get for all SteamIDs a Exception:

e.g Steam ID: 76561198000314037
The specified profile could not be found.
file: steam_id.rb location: fetch line: 79

But if i call:
http://steamcommunity.com/profiles/76561198000314037?xml=1
i get a result...

**Comment by koraktor** [comment]
If you call e.g. `SteamId.new('76561198000314037')` this won't map to http://steamcommunity.com/profiles/76561198000314037, but to http://steamcommunity.com/id/76561198000314037 - because you provided a `String` and not a `Numeric`.

If you only have Strings with the numeric SteamIDs you should call it like `SteamId.new(string_steam_id.to_i)`.

To get back to your initial request: I don't think a general matching against a Regex is a good idea, because the user usually knows what kind of SteamID he supplies. And a simple `.to_i` is enough.

**Comment by idev** [comment]
Ok, i just check before:

  unless steam_id.match(/\d{17}/).nil?
    steam_id = steam_id.to_i
  end

Thanks for your help!
