### ISSUE TITLE
Match with friend

### ISSUE THREAD

**Issue by sdsDenis** [koraktor/steam-condenser#311]
Hello, Koraktor,
I'd like to determine whether the player was playing some odinary match(not lobby) alone or with his friend(s). Is it possible to determine using api?

**Comment by koraktor** [comment]
To be honest, I have no idea.
As individual Web API methods (and what you can or cannot do with them) should not be discussed in an issue report I’m closing this.

I’ve seen you already send a mail to the [Google group](http://groups.google.com/group/steam-condenser) so that would be the ideal place for questions like this.
