### ISSUE TITLE
Ruby - Character Encoding Bug?

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#43]
Hey,

i get a 
JSON::GeneratorError: source sequence is illegal/malformed utf-8>
on the following profile:
http://steamcommunity.com/profiles/76561197981630292
Nickname: �?

I will dig in more detail, but it looks like wrong character encoding?

Perhaps its reproducible :)

**Comment by idev** [comment]
His nickname encoded = \357\274?
irb:

> > nick = "\357\274?"
> > => "\357\274?"
> > nick.to_json
> > NoMethodError: undefined method `to_json' for "\357\274?":String
> >     from (irb):2
> > require 'json'
> > => true
> > nick.to_json
> > JSON::GeneratorError: source sequence is illegal/malformed utf-8
> >     from (irb):4:in`to_json'
> >     from (irb):4

**Comment by idev** [comment]
Hm.. seems to be a REXML issue?

**Comment by koraktor** [comment]
This needs some checks. Maybe it's also a problem for Java and PHP.

**Comment by koraktor** [comment]
Small update: This issue affects all three implementations.

**Comment by koraktor** [comment]
Fixed parsing of community data with Unicode characters

Closed by 0219a8f32802319b6678da4064e7cd74ea7610b3

**Comment by koraktor** [comment]
There was another patch fixing this issue completely: 6f024cde2c1fada28e43aba88866d925fcb8b385

**Comment by idev** [comment]
Hey, thank you for your fast response, i no longer get the malformed error.

But the Nickname look different, i now get:
ï¼?
but it should be:
�?

or is this behavior correct? Have it to convert it back?
Greetings

**Comment by koraktor** [comment]
To be honest, I don't think my fix was a good idea. I just checked the raw hex values of the nickname. And this is `efbc` wich is pretty awkward. As far as I know, this is an illegal unicode character and shouldn't be allowed at all.

I'll revert my changes from yesterday as they introduced problems with legal characters. Maybe there's a better workaround, but this problem seems to be very special and this needs very special treatment. Some sort of filter replacing illegal characters may be a good idea.

**Comment by idev** [comment]
ok!
Perhaps REXML illegal character regex is wrong?
http://ruby-doc.org/core/classes/REXML/Text.html
Can you help me to define a regex which characters are illegal to remove them?

**Comment by koraktor** [comment]
Sorry, for now I have to change this to won't fix because Steam Condenser's functionality isn't really affected. If I find a way to get around this quickly, I may open it again, but right now I don't want to bloat the code with some workaround to fix encoding errors encountered in a few profiles that shouldn't be there if Steam checked this itself.
