### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#77]
Create a .gitignore for every language instead of global .gitignore.
The specific gitignores would be placed in the language directories.

**Comment by koraktor** [comment]
I know there are subdirectory .gitignores, but what specific advantage would they provide?

**Comment by txdv** [comment]
It would avoid conflicts when merging for example other branches with new languages.
Furthermore it would be possible, though very unlikely, that some files which are ignored in one language, shouldn't be ignored in another.

**Comment by koraktor** [comment]
I get your point. That's why the ignored files are prefixed with their language directory in the .gitignore. So this shouldn't be a problem. Basically you're right, and I already thought about splitting Steam Condenser into separate repositories (including them as submodules in a main repository). This would definitely be a use case for separate .gitingores.
Nevertheless, splitting the .gitignore isn't a huge problem. So I'll probably do this in the near future.

**Comment by txdv** [comment]
Seperate repositories would be a little bit tooo harsh, maybe seperate language branches and one master branch including all of them.

**Comment by koraktor** [comment]
Split up .gitignore for individual languages

Closed by 0b91ce9ef528375bf43c7b214728f0bed5c92636
